In [95]:
import tensorflow as tf
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler   
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, ReLU, PReLU, ELU, LeakyReLU, Dropout

In [96]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [97]:
geography=pd.get_dummies(df['Geography'], drop_first=True)
gender=pd.get_dummies(df['Gender'], drop_first=True)

In [98]:
print(geography)
print(gender)

      Germany  Spain
0       False  False
1       False   True
2       False  False
3       False  False
4       False   True
...       ...    ...
9995    False  False
9996    False  False
9997    False  False
9998     True  False
9999    False  False

[10000 rows x 2 columns]
       Male
0     False
1     False
2     False
3     False
4     False
...     ...
9995   True
9996   True
9997  False
9998   True
9999  False

[10000 rows x 1 columns]


In [99]:
df=df.drop(columns=['Geography','Gender'], axis=1)

In [100]:
df

RowNumber  CustomerId    Surname  CreditScore  Age  Tenure    Balance  \
0             1    15634602   Hargrave          619   42       2       0.00   
1             2    15647311       Hill          608   41       1   83807.86   
2             3    15619304       Onio          502   42       8  159660.80   
3             4    15701354       Boni          699   39       1       0.00   
4             5    15737888   Mitchell          850   43       2  125510.82   
...         ...         ...        ...          ...  ...     ...        ...   
9995       9996    15606229   Obijiaku          771   39       5       0.00   
9996       9997    15569892  Johnstone          516   35      10   57369.61   
9997       9998    15584532        Liu          709   36       7       0.00   
9998       9999    15682355  Sabbatini          772   42       3   75075.31   
9999      10000    15628319     Walker          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0                 1          1               1        101348.88       1  
1                 1          0               1        112542.58       0  
2                 3          1               0        113931.57       1  
3                 2          0               0         93826.63       0  
4                 1          1               1         79084.10       0  
...             ...        ...             ...              ...     ...  
9995              2          1               0         96270.64       0  
9996              1          1               1        101699.77       0  
9997              1          0               1         42085.58       1  
9998              2          1               0         92888.52       1  
9999              1          1               0         38190.78       0  

[10000 rows x 12 columns]

In [101]:
df=pd.concat([df,geography,gender], axis=1)

In [102]:
x=df.drop(columns=['RowNumber','CustomerId','Surname','Exited'])   #As they are not very important in predicting Outcomes so we droping them.
y=df['Exited']   #We have to predict it.

In [103]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0               1        101348.88    False  False  False  
1               1        112542.58    False   True  False  
2               0        113931.57    False  False  False  
3               0         93826.63    False  False  False  
4               1         79084.10    False   True  False

In [104]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [105]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [106]:
sc=StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [107]:
print(x_train.shape)
x_train

(8000, 11)


array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.57946723,
         1.73494238,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]])

In [108]:
print(x_test.shape)
x_test

(2000, 11)


array([[-0.57749609, -0.6557859 , -0.69539349, ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.29729735,  0.3900109 , -1.38944225, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.52560743,  0.48508334, -0.3483691 , ..., -0.57946723,
         1.73494238, -1.09499335],
       ...,
       [ 0.81311987,  0.77030065,  0.69270405, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.41876609, -0.94100321, -0.3483691 , ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.24540869,  0.00972116, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]])

In [109]:
# intialize the Sequential

classifier=Sequential()

In [110]:
# we hae to give input layer
classifier.add(Dense(units=11, activation='relu'))
# here dense is the layer 
# units are no of inputs or neurons
# activation which is relu will be applied in next step 



In [111]:
# lets add hidden layer
classifier.add(Dense(units=5, activation='relu'))
classifier.add(Dropout(0.3))
# here dense is the layer 
# units are no of neurons
# activation which is relu will be applied in next step 



In [112]:
# lets add second hidden layer
classifier.add(Dense(units=4, activation='relu'))
# here dense is the layer 
# units are no of neurons
# activation which is relu will be applied in next step 


In [113]:
# lets add output layer
classifier.add(Dense(1, activation='sigmoid'))
# here dense is the layer 
# units are no of neurons
# activation which is sigmoid as this is a classification problem so we will use sigmoid


In [114]:
# lets check the ANN Model

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Adam is one of the best optimizer so far
# here as it is binary classification problem so i am using binary_crossentropy
# I am focusing more on accuracy


In [115]:
# by default Adam use learning rate of 0.01 if i want to change it

import tensorflow
optimizerr=tensorflow.keras.optimizers.Adam(learning_rate=0.001)

In [116]:
classifier.compile(optimizer=optimizerr, loss='binary_crossentropy', metrics=['accuracy'])

In [117]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    min_delta=0.00001,  
    patience=20,
    verbose=1,
    mode='auto',
    baseline=None,
    restore_best_weights=True  # 'false' should be 'True'
)


In [ ]:
model=classifier.fit(x_train,y_train, validation_split=0.33,batch_size=10,epochs=1000,callbacks=early_stopping)

Epoch 1/1000


536/536 ━━━━━━━━━━━━━━━━━━━━ 12s 14ms/step - accuracy: 0.5623 - loss: 0.7041 - val_accuracy: 0.7917 - val_loss: 0.4726
Epoch 2/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.7954 - loss: 0.4751 - val_accuracy: 0.7902 - val_loss: 0.4382
Epoch 3/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.8014 - loss: 0.4287 - val_accuracy: 0.7940 - val_loss: 0.4247
Epoch 4/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - accuracy: 0.8113 - loss: 0.4218 - val_accuracy: 0.8152 - val_loss: 0.4103
Epoch 5/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - accuracy: 0.8334 - loss: 0.4014 - val_accuracy: 0.8330 - val_loss: 0.3976
Epoch 6/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - accuracy: 0.8379 - loss: 0.3943 - val_accuracy: 0.8436 - val_loss: 0.3837
Epoch 7/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.8407 - loss: 0.3798 - val_accuracy: 0.8466 - val_loss: 0.3796
Epoch 8/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - accuracy: 0.8453 - loss: 0.3741 - val_

In [ ]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>=0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step


In [ ]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
cm
 

array([[1520,   87],
       [ 198,  195]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_pred,y_test)
score

0.8575